### PR TITLE
Refactor Github Actions after discussions with Tom

### PR DESCRIPTION
**Pull request by gilesknap**
This has worked out reasonably well.

I currently show coverage to 2 decimals in the badge. Would you prefer integer as we had before?

I'm not totally happy with the granularity of worflows/jobs in GA but it is workable and it will probably improve. At present it feels like workflow control and VMs are too tightly coupled - I'd like some of the workflow control in a single VM, and the same filtering for jobs that actions have.

### CODE REVIEW

**Comment by thomascobb** [comment]
Have we just added a race condition between the two jobs on two VMs that both force push to gh-pages?

**Comment by gilesknap** [comment]
maybe. it looks like the action uses a temporary branch and this might make it OK. looking into more detail ...

**Comment by gilesknap** [comment]
So it does
`git push --force origin temporaryLocalBranch:gh-pages`

therefore there is a race condition.

I could pull the docs job back into the workflow and make it dependent on build so it runs sequentially. 
That is annoying because:

-  it wastes time since the job used to run in parallel
-  it will require 'ifs' for each action because bizarrely  there is no if at the job level (this is the kind of issue I was alluding to in the first comment - https://github.community/t/path-filtering-for-jobs-and-steps/16447/12)

OR I could look into why the gp-pages action thinks it needs to force push and at the very least give it a parameter to not force push.

**Comment by gilesknap** [comment]
Changing the behaviour of gh-pages deploy is not well received by the author and he's probably correct in suggesting we are asking for trouble doing it anyway. https://github.com/JamesIves/github-pages-deploy-action/discussions/529#discussioncomment-163487 

I'm looking at restructuring and it is really annoying because every action in the docs job would require an 'if' filter. I'm trying to come up with some other approach ...

**Comment by thomascobb** [comment]
I guess we could collapse all the steps into a single custom action, shell script or python script that we guard with the if statement?

**Comment by gilesknap** [comment]
What I have at the moment is quite tidy and easy to customise. Embedding everything in an action would make it harder for people to add custom steps, I guess. 

Having said that, I've not yet come up with fix to the race condition that maintains the 'tidy' status.

**Comment by thomascobb** [comment]
Ok, another option for you, push the coverage badge to another branch called "coverage-badge", and link to it with https://raw.githubusercontent.com/PandABlocks/PandABlocks-client/coverage-badge/coverage-badge.svg

**Comment by gilesknap** [comment]
That is what I was looking for - some way to URL ref a different branch! thanks.
________________________________

**Comment by gilesknap** [comment]
Nearly done, but I seem to have broken gh-pages ability to notice the updates. It sees what I have pushed if I manually tweak one of the files from github.

It may be date related https://stackoverflow.com/questions/20422279/github-pages-are-not-updating

I wonder if git is using SOURCE_DATE_EPOCH ???


Will have another go at this after walking the dog since I'm not around tomorrow ...


________________________________

**Comment by gilesknap** [comment]
accepting to test gh-pages deploy

**Pull request merged**
