### PR TITLE
added a break condition to `_ctrl_read_forever`

### PR DESCRIPTION
**Pull request by evalott100**
Breaks out after a constant number of empty bytestrings have been received in a row.

### CODE REVIEW

**Comment by evalott100** [comment]
Tested against the real panda and https://github.com/PandABlocks/PandABlocks-ioc/pull/108

**Comment by AlexanderWells-diamond** [comment]
Should have a unit test added?

**Comment by evalott100** [comment]
> Should have a unit test added?

Agreed, that's it added

**Review by AlexanderWells-diamond — COMMENTED** [review]
I am missing the context of these empty packets. What situation(s) cause them to be sent, and what should the behaviour in the rest of this system be when one is received? What about multiple (as this code seems to look for)? 

A second question is what should the restart/retry behaviour be when the connection is terminated; when the `ConnectionError` exception is raised, that'll propogate out and presumably terminate all communication. Is the user expected to manually restart the connection at that point?

Also it may be worth writing a test that sends `_EMPTY_PACKET_RETRIES  - 1` packets, then a valid packet, then a few more empty packets to confirm that the counter resets correctly.

**Comment by coretl** [comment]
Context:
- When the PandA disconnects then `recv` will return an empty string
- The current code will then sit and spin eating all the CPU
- We want to break out of the loop if that happens, and in some way mark the client as "disconnected" so its obvious

@evalott100 I have never seen the connection come back when it gets in that state, did you add the retry code because of something you saw, or just in case?

**Comment by evalott100** [comment]
> @evalott100 I have never seen the connection come back when it gets in that state, did you add the retry code because of something you saw, or just in case?

Nothing I noticed, it's just in case.

**Comment by AlexanderWells-diamond** [comment]
> * We want to break out of the loop if that happens, and in some way mark the client as "disconnected" so its obvious

[PythonSoftIOC #157](https://github.com/dls-controls/pythonSoftIOC/pull/157) is currently under review that should allow this behaviour.

>  * The current code will then sit and spin eating all the CPU

The more I read around this the more I am believing that, as soon as we see an empty byte response, the connection is gone and is not coming back. I'm more used to using sockets directly, rather than asyncio's wrappers around them, but for a socket if you receive a "0" from a `recv()` call then the other end is disconnected. I can't see exactly what the asyncio StreamReader code is doing, but it seems to be interpreting "no data" as `b''`, which agrees with [the documentation](https://docs.python.org/3/library/asyncio-stream.html#asyncio.StreamReader.read).  So I believe that if we see a `b''` response, we should just terminate immediately.

**Comment by coretl** [comment]
> > @evalott100 I have never seen the connection come back when it gets in that state, did you add the retry code because of something you saw, or just in case?
> 
> Nothing I noticed, it's just in case. Happy to take it out if you think it's unneccesary?

Yes please

**Review by AlexanderWells-diamond — APPROVED** [review]
Change looks good. How visible is the exception message when the disconnect occurs i.e. where does it get logged to?

**Comment by evalott100** [comment]
> Change looks good. How visible is the exception message when the disconnect occurs i.e. where does it get logged to?

I'll add another loggging.error

**Pull request merged**
